### ISSUE TITLE
Invalid Params

### ISSUE THREAD

**Issue by acasanova** [StreamBoat/kodi_jsonrpc#2]
I'm trying to run Addons.ExecuteAddon. I turned kodi debugging on and I can see that the request is made but I get the following response back:
`Kodi error (-32602): Invalid params.`

The log shows the following when the request is made
`{"id":1,"method":"Addons.ExecuteAddon","params":{"addonid":"http://fusion.xbmchub.com/"},"jsonrpc":"2.0"}`

I'm not sure what params I'm missing. I tried all properties from the wiki.
Here is the code below. 

````
func addRepo(repo string) {

	connect()
	defer kodi.Close()
	params := make(map[string]interface{}, 1)
	params["addonid"] = repo
	//params["params"] = nil
	//params["wait"] = true

	request := _kodi.Request{Method: `Addons.ExecuteAddon`, Params: &params}
	response, _ := kodi.Send(request, true)
	// wait indefinitely for response (timeout 0)
	result, err := response.Read(0)

	if err != nil {
		panic(fmt.Sprintf(`Kodi responded with error: %v`, err))
	}

	fmt.Println(result, response)
}
````

Am I building the params map properly? Is there anyway i can access a more descriptive error message?

**Comment by pdf** [comment]
Your `addonid` can't be right - addons are in the form `script.python.whatever` or `plugin.video.whatever`, you can get a list of plugins via the `Addons.GetAddons` RPC method.

**Comment by pdf** [comment]
Did you get this sorted out?

**Comment by pdf** [comment]
Closed due to inactivity, please feel free to post a comment if you need this re-opened.
