### ISSUE TITLE
Connection.writer and Connection.reader goroutines are not stopped after Close()

### ISSUE THREAD

**Issue by quhar** [StreamBoat/kodi_jsonrpc#3]
After `Connection.Close()` is executed `Connection.writer` and `Connection.reader` gorutines are not terminated when main goroutine is still running. As `Close()` closes but  `Connection.write` channel writer goroutine is receving nil values from it and bombards Kodi with empty requests. Example code and output are [here] (https://gist.github.com/quhar/d8b47444e67b7160362b).
I've created small [fix] (https://github.com/quhar/kodi_jsonrpc/commit/b27e9292f124e48b278078d528ddedbed10436e1), but as I'm very new to Go I'm not sure if this is the way to do it.

**Comment by pdf** [comment]
This was almost the first Go code I wrote and I've been seriously considering rewriting it, I'll take a look and see what the best way to fix this is.

**Comment by pdf** [comment]
Please take a look at https://github.com/pdf/kodirpc which is a rewrite that does not use the same pattern, and should be unaffected by this issue.
